#!/usr/bin/env python
# -*- coding: US-ASCII -*-
#
# generated by wxGlade 0.6.8 on Thu Mar  6 15:07:47 2014
#

__author__ = 'Zack Gainsforth'
__copyright__ = 'Copyright 2016, Zack Gainsforth'
__email__ = 'zsg@gainsforth.com'

# TODO Print out k-facs used.
# TODO Site occupation and endmember fitter.  A py file for each system.
# TODO Add and compute errorbars
# TODO Output quant from minerals and delta.
# TODO Subphase reporter.

import os
import pickle
import platform

# WSLg normally selects Wayland for wxGTK.  Wayland intentionally leaves
# top-level placement to its compositor, so saved phase-figure positions are
# not reproducible there.  WSLg also supplies X11; select it before wx opens a
# display, unless the user has explicitly chosen a backend of their own.
if (os.environ.get('WSL_DISTRO_NAME') or
        'microsoft' in platform.release().lower()) and not os.environ.get('GDK_BACKEND'):
    os.environ['GDK_BACKEND'] = 'x11'

import wx
import builtins
from copy import deepcopy
import xml.etree.ElementTree as ElementTree
try:
    import wx.svg as wxsvg
except ImportError:
    wxsvg = None
from numpy import *
import ReportResults
from collections import OrderedDict
import MyPython
import importlib

# begin wxGlade: dependencies
import gettext
# end wxGlade

import PhysicsBasics as pb
from MyPython import *
import CountsToQuant
import PhaseFit
import StoichiometryCore
import ProjectPackage

def import_function_from_path(function_name, path):
    spec = importlib.util.spec_from_file_location("module_name", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return getattr(module, function_name)

# Usage
wx.SystemOptions.SetOption('mac.listctrl.always_use_generic', '1')

# begin wxGlade: extracode
from wx.lib.mixins.listctrl import TextEditMixin

# The pickle filename that used to store the temporory data.
PICKLE_FILE = 'save.dat'

# Add an item to the pickle file.
def add_to_pickle(path, item):
    with open(path, 'ab') as file:
        pickle.dump(item, file, pickle.HIGHEST_PROTOCOL)
        
class EditableTextListCtrl(wx.ListCtrl, TextEditMixin):
    def __init__(self, parent, ID, pos=wx.DefaultPosition,
                size=wx.DefaultSize, style=0):
        wx.ListCtrl.__init__(self, parent, ID, pos, size, style)
        TextEditMixin.__init__(self)
# end wxGlade

    EditableColumns = None
    def SetEditableColumns(self, ColNums=None):
        self.EditableColumns = ColNums

    # This opens when the user edits an item in the ListCtrl.
    def OpenEditor(self, col, row):
        # IF this is not an editable ListCtrl, then EditableColumns == None.  Nothing to do here in this case.  Defer
        #  to super.
        if self.EditableColumns == None:
            print ("Warning: It appears you are using an EditableTextListCtrl where there are no editable columns.")
            return

        # The only editable entry is column 1 (counts for a given element.)
        if col in self.EditableColumns:
            super(EditableTextListCtrl, self).OpenEditor(col, row)


class SVGFigureFrame(wx.Frame):
    """A resizable, zoomable wx viewer for one portable SVG artifact."""

    def __init__(self, parent, title, svg_payload, position=wx.DefaultPosition,
                 restored_geometry=None):
        restored_size = restored_geometry[1] if restored_geometry is not None else (1, 1)
        wx.Frame.__init__(self, parent, title='Phase Analysis Figure - ' + title,
                          pos=position, size=restored_size)
        self._svg_image = wxsvg.SVGimage.CreateFromBytes(svg_payload)
        self._native_width = builtins.max(1, int(builtins.round(self._svg_image.width)))
        self._native_height = builtins.max(1, int(builtins.round(self._svg_image.height)))
        self._scale = 1.0
        self._fit_mode = True
        self._pixel_buffer = None
        self._initial_layout = restored_geometry is None
        self._drag_start = None
        self._drag_view_start = None

        panel = wx.Panel(self)
        self._viewer_panel = panel
        outer_sizer = wx.BoxSizer(wx.VERTICAL)
        controls = wx.BoxSizer(wx.HORIZONTAL)
        zoom_out = wx.Button(panel, label='Zoom -')
        zoom_in = wx.Button(panel, label='Zoom +')
        fit = wx.Button(panel, label='Fit')
        controls.Add(zoom_out, 0, wx.ALL, 4)
        controls.Add(zoom_in, 0, wx.ALL, 4)
        controls.Add(fit, 0, wx.ALL, 4)
        controls.Add(wx.StaticText(panel, label='Mouse wheel zooms; left-drag or scrollbars pan.'),
                     0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 8)
        self._controls = controls
        outer_sizer.Add(controls, 0, wx.EXPAND)

        self.scroller = wx.ScrolledWindow(panel)
        self.scroller.SetScrollRate(1, 1)
        self.scroller.SetBackgroundStyle(wx.BG_STYLE_PAINT)
        outer_sizer.Add(self.scroller, 1, wx.EXPAND)
        panel.SetSizer(outer_sizer)
        frame_sizer = wx.BoxSizer(wx.VERTICAL)
        frame_sizer.Add(panel, 1, wx.EXPAND)
        self.SetSizer(frame_sizer)

        zoom_out.Bind(wx.EVT_BUTTON, lambda event: self._zoom(1 / 1.10))
        zoom_in.Bind(wx.EVT_BUTTON, lambda event: self._zoom(1.10))
        fit.Bind(wx.EVT_BUTTON, lambda event: self._fit_image())
        self.scroller.Bind(wx.EVT_PAINT, self._on_paint)
        self.scroller.Bind(wx.EVT_SCROLLWIN, self._on_scroll)
        self.scroller.Bind(wx.EVT_MOUSEWHEEL, self._on_mouse_wheel)
        self.scroller.Bind(wx.EVT_LEFT_DOWN, self._on_left_down)
        self.scroller.Bind(wx.EVT_MOTION, self._on_mouse_motion)
        self.scroller.Bind(wx.EVT_LEFT_UP, self._on_left_up)
        self.Bind(wx.EVT_SIZE, self._on_size)
        if restored_geometry is None:
            wx.CallAfter(self._size_to_native_image)
        else:
            # A restored frame must not be resized after it is mapped: several
            # desktop compositors recascade an owned top-level window when that
            # happens.  Giving wx its final geometry at construction time keeps
            # both its saved position and size intact.
            wx.CallAfter(self._render)

    def _render(self):
        width = builtins.max(1, int(builtins.round(self._native_width * self._scale)))
        height = builtins.max(1, int(builtins.round(self._native_height * self._scale)))
        self.scroller.SetVirtualSize((width, height))
        self.scroller.Refresh(False)

    def _on_paint(self, event):
        """Rasterize only the visible SVG viewport, even at high zoom."""
        client = self.scroller.GetClientSize()
        width = builtins.max(1, client.width)
        height = builtins.max(1, client.height)
        units_x, units_y = self.scroller.GetScrollPixelsPerUnit()
        view_x, view_y = self.scroller.GetViewStart()
        offset_x = view_x * units_x
        offset_y = view_y * units_y
        self._pixel_buffer = bytearray(width * height * 4)
        self._svg_image.RasterizeToBuffer(
            self._pixel_buffer, tx=-offset_x, ty=-offset_y, scale=self._scale,
            width=width, height=height, stride=width * 4)
        bitmap = wx.Bitmap.FromBufferRGBA(width, height, self._pixel_buffer)
        dc = wx.AutoBufferedPaintDC(self.scroller)
        dc.SetBackground(wx.Brush(self.scroller.GetBackgroundColour()))
        dc.Clear()
        self.scroller.PrepareDC(dc)
        dc.DrawBitmap(bitmap, offset_x, offset_y, True)

    def _on_scroll(self, event):
        event.Skip()
        wx.CallAfter(self._render)

    def _fit_image(self):
        available = self.scroller.GetClientSize()
        available_width = builtins.max(1, available.width - 12)
        available_height = builtins.max(1, available.height - 12)
        self._scale = builtins.max(0.05, builtins.min(
            available_width / self._native_width, available_height / self._native_height))
        self._fit_mode = True
        self._render()

    def _size_to_native_image(self):
        """Open at the SVG's native size, including only the viewer controls."""
        self._scale = 1.0
        self._render()
        controls_height = self._controls.CalcMin().height
        self.SetClientSize((self._native_width + 12, self._native_height + controls_height + 12))
        self._initial_layout = False

    def SetSvgPayload(self, svg_payload):
        """Replace the displayed SVG without changing this window's geometry."""
        self._svg_image = wxsvg.SVGimage.CreateFromBytes(svg_payload)
        self._native_width = builtins.max(1, int(builtins.round(self._svg_image.width)))
        self._native_height = builtins.max(1, int(builtins.round(self._svg_image.height)))
        if self._fit_mode:
            self._fit_image()
        else:
            self._render()

    def _zoom(self, factor, focus=None):
        old_scale = self._scale
        old_width = self._native_width * old_scale
        old_height = self._native_height * old_scale
        if focus is None:
            size = self.scroller.GetClientSize()
            focus = wx.Point(size.width // 2, size.height // 2)
        units_x, units_y = self.scroller.GetScrollPixelsPerUnit()
        view_x, view_y = self.scroller.GetViewStart()
        content_x = view_x * units_x + focus.x
        content_y = view_y * units_y + focus.y
        relative_x = content_x / old_width if old_width else 0
        relative_y = content_y / old_height if old_height else 0
        self._scale = builtins.max(0.05, builtins.min(24.0, old_scale * factor))
        self._fit_mode = False
        self._render()
        new_x = relative_x * self._native_width * self._scale - focus.x
        new_y = relative_y * self._native_height * self._scale - focus.y
        self.scroller.Scroll(
            int(builtins.max(0, new_x) / units_x) if units_x else 0,
            int(builtins.max(0, new_y) / units_y) if units_y else 0,
        )

    def _event_position(self, event):
        """Return an event position in the scroller's visible coordinates."""
        return event.GetPosition()

    def _on_mouse_wheel(self, event):
        rotation = event.GetWheelRotation()
        if rotation:
            wheel_delta = event.GetWheelDelta() or 120
            # Preserve fractional touchpad/wheel rotation.  A conventional
            # wheel notch changes scale by only 10%, while smaller rotations
            # produce correspondingly smaller scale steps.
            factor = 1.10 ** (rotation / wheel_delta)
            self._zoom(factor, self._event_position(event))

    def _on_left_down(self, event):
        self._drag_start = self._event_position(event)
        self._drag_view_start = self.scroller.GetViewStart()
        self.scroller.CaptureMouse()

    def _on_mouse_motion(self, event):
        if (self._drag_start is None or self._drag_view_start is None or
                not event.Dragging() or not event.LeftIsDown()):
            event.Skip()
            return
        current = self._event_position(event)
        units_x, units_y = self.scroller.GetScrollPixelsPerUnit()
        start_x, start_y = self._drag_view_start
        self.scroller.Scroll(
            builtins.max(0, int(start_x - (current.x - self._drag_start.x) / units_x)) if units_x else 0,
            builtins.max(0, int(start_y - (current.y - self._drag_start.y) / units_y)) if units_y else 0,
        )
        self._render()

    def _on_left_up(self, event):
        if self.scroller.HasCapture():
            self.scroller.ReleaseMouse()
        self._drag_start = None
        self._drag_view_start = None

    def _on_size(self, event):
        event.Skip()
        if not self._initial_layout and self._fit_mode:
            wx.CallAfter(self._fit_image)




class MyMenuBar(wx.MenuBar):
    def __init__(self, *args, **kwds):
        # Content of this block not found. Did you rename this class?
        pass

    def __set_properties(self):
        # Content of this block not found. Did you rename this class?
        pass

    def __do_layout(self):
        # Content of this block not found. Did you rename this class?
        pass

# end of class MyMenuBar
class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.MainMenu = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_OPEN, _("&Open..."), "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_SAVE, _("&Save Project"), "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_SAVEAS, _("Save Project &As..."), "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(1000, _("Export &Input CSV..."), "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(1001, _("Export &Text Report..."), "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_ABOUT, _("&About"), "", wx.ITEM_NORMAL)
        self.MainMenu.Append(wxglade_tmp_menu, _("File"))
        self.SetMenuBar(self.MainMenu)
        # Menu Bar end
        self.panel_4 = wx.Panel(self, wx.ID_ANY)
        self.ElementsListCtrl = EditableTextListCtrl(self.panel_4, wx.ID_ANY, style=wx.BORDER_SUNKEN | wx.FULL_REPAINT_ON_RESIZE | wx.LC_EDIT_LABELS | wx.LC_REPORT | wx.LC_SINGLE_SEL)
        self.rdioInputType = wx.RadioBox(self.panel_4, wx.ID_ANY, _("Input Type"), choices=[_("Counts"), _("At %"), _("Wt %"), _("Ox Wt %")], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.btnReset = wx.Button(self.panel_4, wx.ID_ANY, _("Reset"))
        self.panel_5 = wx.Panel(self, wx.ID_ANY)
        self.PhasesListCtrl = wx.ListCtrl(self.panel_5, wx.ID_ANY, style=wx.BORDER_SUNKEN | wx.LC_REPORT)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        # The following lines are the parts that need to be samed -- Roger
        self.chkPhaseAnalysis = wx.CheckBox(self.panel_1, wx.ID_ANY, "") #FIXME Phase Analysis Checkbox
        self.cmbPhaseAnalysis = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_READONLY) #FIXME Phase Analysis drop box
        self.chkArbAbsCorrection = wx.CheckBox(self.panel_1, wx.ID_ANY, "") #FIXME Arb abs Checkbox
        self.comboArbAbsCorrection = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_READONLY) #FIXME Arb abs drop box
        self.chkAbsCorr = wx.CheckBox(self.panel_1, wx.ID_ANY, "") #FIXME TEM Thickness Correction
        self.txtAbsCorr = wx.TextCtrl(self.panel_1, wx.ID_ANY, "") #FIXME TEM Thickness Correction
        self.txtTakeoff = wx.TextCtrl(self.panel_1, wx.ID_ANY, _("18")) #FIXME TEM Thickness Correction
        self.label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("g/cm3 * nm"), style=wx.ALIGN_CENTER)
        self.label_1_copy = wx.StaticText(self.panel_1, wx.ID_ANY, _("takeoff in deg"), style=wx.ALIGN_CENTER)
        self.chkKfacs = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        self.comboKfacs = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_READONLY)
        self.chkOByStoichiometry = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
        self.comboStoich = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_READONLY)
        self.btnGo = wx.Button(self.panel_1, wx.ID_ANY, _("Go!"))
        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.txtOutput = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnOpen, id=wx.ID_OPEN)
        self.Bind(wx.EVT_MENU, self.OnSaveInputs, id=1000)
        self.Bind(wx.EVT_MENU, self.OnSaveResults, id=1001)
        self.Bind(wx.EVT_MENU, self.OnSave, id=wx.ID_SAVE)
        self.Bind(wx.EVT_MENU, self.OnSaveAs, id=wx.ID_SAVEAS)
        self.Bind(wx.EVT_MENU, self.OnAbout, id=wx.ID_ABOUT)
        self.Bind(wx.EVT_RADIOBOX, self.OnInputType, self.rdioInputType)
        self.Bind(wx.EVT_BUTTON, self.OnReset, self.btnReset)
        self.Bind(wx.EVT_CHECKBOX, self.OnStoichSelect, self.chkPhaseAnalysis)
        self.Bind(wx.EVT_COMBOBOX, self.OnDetectorSelect, self.cmbPhaseAnalysis)
        self.Bind(wx.EVT_CHECKBOX, self.OnStoichSelect, self.chkArbAbsCorrection)
        self.Bind(wx.EVT_COMBOBOX, self.OnDetectorSelect, self.comboArbAbsCorrection)
        self.Bind(wx.EVT_CHECKBOX, self.OnStoichSelect, self.chkOByStoichiometry)
        self.Bind(wx.EVT_COMBOBOX, self.OnStoichSelect, self.comboStoich)
        self.Bind(wx.EVT_BUTTON, self.OnGo, self.btnGo)
        # end wxGlade

        # First verify that we are running in the home directory (i.e. we should be in the directory containing
        # StoichiometryFitter.py
        #import pdb
        #pdb.set_trace()
        if not os.path.isfile(os.path.join(os.getcwd(), 'StoichiometryFitter.py')):
            MyPython.ReportError('Please ensure the running directory is the directory containing StoichiometryFitter'
                                 '.py')

        self.Bind(wx.EVT_MENU, self.OnAbout, id=wx.ID_ABOUT)

        # Make sure the window never gets too small to see the controls.
        self.SetMinSize((650, 500))

        # Set up the initial conditions for the frame.
        self.InitControls()
        self.CurrentProjectPath = None
        self.CurrentProjectId = None
        self.OriginalSource = None
        self.ArchivedResources = None
        self.ArchivedFingerprint = None
        self.ArchivedInput = None
        self.ArchivedOptions = None
        self.ProjectMetadata = {}
        self.PhaseFigureLayouts = {}

        # Catch the frame closing event so we can ask if we want to save.
        self.Bind(wx.EVT_CLOSE, self.OnClose)

        self.Layout()

    def OnClose(self, evt):
        """OnClose(self, evt): Ask the user if he wants to save before closing.  Not yet implemented."""
        # it = self.ElementsListCtrl.GetItem(0,1)
        # print it.GetText()
        self.ClosePhaseAnalysisFigures()
        self.PhaseFigureLayouts = {}
        self.ProjectMetadata = {}
        self.Destroy()

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Stoichiometry Fitter"))
        self.SetSize((1300, 703))
        self.ElementsListCtrl.SetMinSize((200, 100))
        self.rdioInputType.SetMinSize((200,120))
        self.rdioInputType.SetSelection(0)
        self.btnReset.SetMinSize((200,20))
        self.panel_4.SetMinSize((200, -1))
        self.PhasesListCtrl.SetMinSize((300, 300))
        self.panel_5.SetMinSize((305,300))
        self.chkPhaseAnalysis.SetValue(1)
        self.chkArbAbsCorrection.SetValue(1)
        self.label_1.SetMinSize((77, 22))
        self.label_1_copy.SetMinSize((100, 22))
        self.chkKfacs.Enable(False)
        self.chkOByStoichiometry.SetValue(1)
        self.panel_1.SetMinSize((300, -1))
        self.txtOutput.SetFont(wx.Font(11, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.FlexGridSizer(1, 1, 0, 0)
        sizer_2 = wx.FlexGridSizer(1, 4, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(8, 1, 0, 0)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, _("Oxygen by stoichiometry?")), wx.HORIZONTAL)
        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, _("Apply k-factors for:")), wx.HORIZONTAL)
        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, _("TEM Thickness Correction")), wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_5_copy = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, _("Arbitrary absorption")), wx.HORIZONTAL)
        sizer_14 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, _("Phase Analysis")), wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.FlexGridSizer(3, 1, 0, 0)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9.Add(self.ElementsListCtrl, 0, wx.ALL | wx.EXPAND, 2)
        sizer_6.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_10.Add(self.rdioInputType, 0, wx.EXPAND, 0)
        sizer_6.Add(sizer_10, 0, wx.EXPAND, 0)
        sizer_8.Add(self.btnReset, 0, wx.ALL | wx.EXPAND, 2)
        sizer_6.Add(sizer_8, 0, wx.EXPAND, 0)
        self.panel_4.SetSizer(sizer_6)
        sizer_6.AddGrowableRow(0)
        sizer_2.Add(self.panel_4, 0, wx.EXPAND, 0)
        sizer_11.Add(self.PhasesListCtrl, 0, wx.ALL | wx.EXPAND, 2)
        self.panel_5.SetSizer(sizer_11)
        sizer_2.Add(self.panel_5, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        sizer_14.Add(self.chkPhaseAnalysis, 0, 0, 0)
        sizer_14.Add(self.cmbPhaseAnalysis, 1, wx.ALL | wx.EXPAND, 2)
        grid_sizer_1.Add(sizer_14, 1, wx.EXPAND, 0)
        sizer_5_copy.Add(self.chkArbAbsCorrection, 0, 0, 0)
        sizer_5_copy.Add(self.comboArbAbsCorrection, 1, wx.ALL | wx.EXPAND, 2)
        grid_sizer_1.Add(sizer_5_copy, 1, wx.EXPAND, 0)
        sizer_3.Add(self.chkAbsCorr, 0, 0, 0)
        sizer_12.Add(self.txtAbsCorr, 1, wx.EXPAND, 0)
        sizer_12.Add(self.txtTakeoff, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_13.Add(self.label_1, 0, wx.EXPAND, 0)
        sizer_13.Add(self.label_1_copy, 0, wx.EXPAND, 0)
        sizer_3.Add(sizer_13, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_4.Add(self.chkKfacs, 0, 0, 0)
        sizer_4.Add(self.comboKfacs, 1, wx.ALL | wx.EXPAND, 2)
        grid_sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_5.Add(self.chkOByStoichiometry, 0, 0, 0)
        sizer_5.Add(self.comboStoich, 1, wx.ALL | wx.EXPAND, 2)
        grid_sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_7.Add(self.btnGo, 0, wx.ALL | wx.EXPAND, 2)
        grid_sizer_1.Add(sizer_7, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(grid_sizer_1)
        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableRow(7)
        grid_sizer_1.AddGrowableCol(0)
        sizer_2.Add(self.panel_1, 0, wx.EXPAND, 0)
        sizer_2.Add(self.txtOutput, 1, wx.ALL | wx.EXPAND, 2)
        sizer_2.AddGrowableRow(0)
        sizer_2.AddGrowableCol(3)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.AddGrowableRow(0)
        sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def LoadStoichiometryFile(self):
        # Load the stoichiometry list.  It's two column.  First is the element name.  Second is the atom's charge.
        # The converter removes ensures we have floats.
        try:
            self.Stoich = genfromtxt('ConfigData/Stoich ' + self.comboStoich.StringSelection + '.csv', dtype=None,
                                     comments='#', delimiter=',', skip_header=1, converters={1: lambda s: float(s)})
        except:
            ReportError('Could not read stoichiometry file.')

    def InitControls(self):
        """InitControls(self):
        Fills in the Elements list, sets up checkboxes, and fills in the phases list.
        """
        # Read in saved data if there is a pickle file in the directory -- Roger
        if os.path.exists(PICKLE_FILE):
            with open(PICKLE_FILE, 'rb') as file:
                try:
                    PhaseA = pickle.load(file)
                    ArbitraryA = pickle.load(file)
                    TEM1 = pickle.load(file)
                    TEM2 = pickle.load(file)
                    k_factor = pickle.load(file)
                    stoich333 = pickle.load(file)

                    k_factor_cb = pickle.load(file)
                    PhaseA_cb = pickle.load(file)
                    ArbitraryA_cb = pickle.load(file)
                    TEM_cb = pickle.load(file)
                    stoich333_cb = pickle.load(file)
                except EOFError:
                    pass

        # chkAbsCorr FIXME
        if os.path.exists(PICKLE_FILE):
            self.chkAbsCorr.SetValue(TEM_cb)

        """ PHASES LIST CONTROL"""
        # Initialize the Phases list control.
        self.PhasesListCtrl.InsertColumn(0, 'Phase')

        # Load the list of phases.  It's two column.  First is the human name for the phase.  Second is the formula in the format 'Si1 O2' for SiO2.
        # The converter removes whitespace from the formula column so we can have variable column widths.
        self.Phases = genfromtxt('ConfigData/Phases.csv', dtype=None, comments='#', delimiter=',',
                                 converters={1: lambda s: str(s).lstrip()})

        # Now loop through each one, and add it to the phases list box.
        i = 0
        for Phase, Formula in self.Phases:
            self.PhasesListCtrl.InsertItem(i, Phase)
            i += 1

        # Make sure the column is wide enough to show everything.
        self.PhasesListCtrl.SetColumnWidth(0, 300)
        if os.path.exists(PICKLE_FILE):
            self.txtAbsCorr.SetValue(str(TEM1))
            self.txtTakeoff.SetValue(str(TEM2))

        """ POPULATE KFACS PULLDOWN """
        for file in os.listdir('ConfigData'):
            if file.startswith('kfacs') and file.endswith('.csv'):
                kfacsname = file.split('kfacs ')[1].split('.csv')[0]
                self.comboKfacs.Append(kfacsname)
        self.comboKfacs.Select(0)
        if os.path.exists(PICKLE_FILE):
            self.comboKfacs.SetValue(k_factor)
            # For counts we will want the kfactors.
            self.chkKfacs.SetValue(k_factor_cb) #FIXME
        else:
            self.chkKfacs.SetValue(True)
        

        """ POPULATE PHASE ANALYSIS PULLDOWN """
        for file in os.listdir(StoichiometryCore.PHASE_ANALYSIS_DIR):
            if file.endswith('.py') and file not in ('__init__.py', 'contract.py', 'ternary_diagram.py'):
                phasename = os.path.splitext(file)[0]
                self.cmbPhaseAnalysis.Append(phasename)
        self.cmbPhaseAnalysis.Select(0)
        if os.path.exists(PICKLE_FILE):
            self.cmbPhaseAnalysis.SetValue(PhaseA)
            self.chkPhaseAnalysis.SetValue(PhaseA_cb) # FIXME
        else:
            self.chkPhaseAnalysis.SetValue(False)

        """ POPULATE ARBITRARY ABSORPTION PULLDOWN """
        for file in os.listdir('ConfigData'):
            if file.startswith('Absorption ') and file.endswith('.csv'):
                kfacsname = file.split('Absorption ')[1].split('.csv')[0]
                self.comboArbAbsCorrection.Append(kfacsname)
        self.comboArbAbsCorrection.Select(0)
        if os.path.exists(PICKLE_FILE):
            self.comboArbAbsCorrection.SetValue(ArbitraryA)
            self.chkArbAbsCorrection.SetValue(ArbitraryA_cb) # FIXME
        # The user will have to select if he wants an absorption correction.
        else:
            self.chkArbAbsCorrection.SetValue(False) # FIXME

        """ POPULATE THE INPUT SOURCE """
        # Start with counts as the selected item.
        self.rdioInputType.SetSelection(0)

        """ POPULATE THE STOICHIOMETRY FITTER """
        for file in os.listdir('ConfigData'):
            if file.startswith('Stoich') and file.endswith('.csv'):
                stoichname = file.split('Stoich ')[1].split('.csv')[0]
                self.comboStoich.Append(stoichname)
        self.comboStoich.Select(0)
        if os.path.exists(PICKLE_FILE):
            self.comboStoich.SetValue(stoich333)
            self.chkOByStoichiometry.SetValue(stoich333_cb) #FIXME
        # Default to using O by stoichiometry.
        else:
            self.chkOByStoichiometry.SetValue(True) #FIXME

        self.LoadStoichiometryFile()

        """ ELEMENTS LIST CONTROL"""
        #Initialize the Elements list control.  Add a row for every element.
        self.ElementsListCtrl.InsertColumn(0, 'Element')
        self.ElementsListCtrl.SetColumnWidth(0, 60)
        self.ElementsListCtrl.InsertColumn(1, 'Counts')
        self.ElementsListCtrl.SetColumnWidth(1, 60)
        self.ElementsListCtrl.InsertColumn(2, 'Charge') # Used for stoichiometry calculation.
        self.ElementsListCtrl.SetColumnWidth(2, 60)
        for Z in range(1, pb.MAXELEMENT + 1):
            self.ElementsListCtrl.InsertItem(Z - 1, pb.ElementalSymbols[Z])
            self.ElementsListCtrl.SetItem(Z - 1, 1, '0')
        # The stoichometry column is separately populated by this function...
        self.OnStoichSelect(None)
        self.UpdateInputType('Counts')


    def OnReset(self, event):  # wxGlade: MyFrame.<event_handler>
        """OnReset(self, event):
            Set all the elements back to zero so the user can type in a new sample.
        """

        # Sometimes the person doesn't hit enter after editing a value in the ElementsListControl.  In this case,
        # we need to end his edit or the value doesn't get saved.
        self.ElementsListCtrl.CloseEditor(None)
        self.ClosePhaseAnalysisFigures()
        self.PhaseFigureLayouts = {}
        self.ProjectMetadata = {}

        for Z in range(1, pb.MAXELEMENT + 1):
            self.ElementsListCtrl.SetItem(Z - 1, 1, '0')
        if hasattr(self, 'LastAnalysisResult'):
            del self.LastAnalysisResult
        self.OriginalSource = None
        self.CurrentProjectPath = None
        self.CurrentProjectId = None
        event.Skip()

    def _analysis_state_from_controls(self):
        """Capture editable state without performing a calculation."""
        self.ElementsListCtrl.CloseEditor(None)
        values = zeros(pb.MAXELEMENT)
        for Z in range(1, pb.MAXELEMENT + 1):
            text = self.ElementsListCtrl.GetItem(Z - 1, 1).GetText().strip()
            values[Z - 1] = float(text) if text else 0.0

        stoichiometry = None
        if self.chkOByStoichiometry.IsChecked():
            stoichiometry = []
            for Z in range(1, pb.MAXELEMENT + 1):
                text = self.ElementsListCtrl.GetItem(Z - 1, 2).GetText().strip()
                if text == 'n/a':
                    raise ValueError('Stoichiometry is enabled but charge values are unavailable.')
                stoichiometry.append(float(text))

        absorption_correction = 0.0
        takeoff = 18.0
        if self.chkAbsCorr.IsChecked():
            absorption_correction = float(self.txtAbsCorr.GetValue()) / 1000.0
            takeoff = float(clip(float(self.txtTakeoff.GetValue()), 0.1, 90))

        analysis_input = StoichiometryCore.AnalysisInput(
            values=dict(StoichiometryCore.vector_to_element_dict(values)),
            input_type=self.rdioInputType.StringSelection,
            stoichiometry=stoichiometry,
            stoichiometry_name=self.comboStoich.StringSelection,
        )
        options = StoichiometryCore.AnalysisOptions(
            kfactors=self.comboKfacs.StringSelection if self.chkKfacs.IsChecked() else None,
            arbitrary_absorption=(self.comboArbAbsCorrection.StringSelection
                                  if self.chkArbAbsCorrection.IsChecked() else None),
            absorption_correction=absorption_correction,
            takeoff=takeoff,
            selected_phases=GetSelectedItemsFromListCtrl(self.PhasesListCtrl),
            phase_analysis=(self.cmbPhaseAnalysis.StringSelection
                            if self.chkPhaseAnalysis.IsChecked() else None),
        )
        ProjectPackage.validate_analysis_input(analysis_input)
        ProjectPackage.validate_options(options)
        return analysis_input, options, values

    def OnGo(self, event):  # wxGlade: MyFrame.<event_handler>
        # Sometimes the person doesn't hit enter after editing a value in the ElementsListControl.  In this case,
        # we need to end his edit or the value doesn't get saved.
        self.ElementsListCtrl.CloseEditor(None)

        # Remove the pickle file and make a new one later.
        if os.path.exists(PICKLE_FILE):
            os.remove(PICKLE_FILE)

        try:
            AnalysisInput, AnalysisOptions, Counts = self._analysis_state_from_controls()
        except Exception as exc:
            wx.MessageBox(str(exc), 'Please correct input:', style=wx.OK)
            return

        archived_resources = None
        if (getattr(self, 'ArchivedResources', None) is not None and
                AnalysisInput == getattr(self, 'ArchivedInput', None) and
                AnalysisOptions == getattr(self, 'ArchivedOptions', None)):
            archived_resources = self.ArchivedResources

        try:
            self.LastAnalysisResult = StoichiometryCore.run_analysis(
                AnalysisInput, options=AnalysisOptions, resolved_resources=archived_resources)
        except Exception as exc:
            wx.MessageBox(str(exc), 'Analysis failed', style=wx.OK)
            return

        self.Counts = Counts
        if archived_resources is not None:
            current_fingerprint = StoichiometryCore.calculation_fingerprint(
                archived_resources, AnalysisOptions.phase_analysis)
            stored_algorithms = (getattr(self, 'ArchivedFingerprint', None) or {}).get('algorithm_hashes', {})
            if stored_algorithms and stored_algorithms != current_fingerprint.get('algorithm_hashes', {}):
                self.LastAnalysisResult.warnings.insert(
                    0, 'This project was calculated with a different algorithm fingerprint; rerun results may differ from the archived snapshot.')
        self.ArchivedResources = self.LastAnalysisResult.resources
        self.ArchivedFingerprint = self.LastAnalysisResult.calculation_fingerprint
        self.ArchivedInput = self.LastAnalysisResult.input
        self.ArchivedOptions = self.LastAnalysisResult.options
        self.txtOutput.SetValue(self.LastAnalysisResult.report_text)
        for warning in self.LastAnalysisResult.warnings:
            self.txtOutput.AppendText('\nWarning: %s\n' % warning)
        if self.LastAnalysisResult.figures:
            figure_warning = self.ShowPhaseAnalysisFigures(self.LastAnalysisResult.figures)
            if figure_warning:
                self.LastAnalysisResult.warnings.append(figure_warning)
                self.txtOutput.AppendText('\nWarning: %s\n' % figure_warning)
        else:
            self.ClosePhaseAnalysisFigures()

        # Saving the entry to the pickle file. Fixed by Roger
        add_to_pickle(PICKLE_FILE, self.cmbPhaseAnalysis.StringSelection)
        add_to_pickle(PICKLE_FILE, self.comboArbAbsCorrection.StringSelection)
        add_to_pickle(PICKLE_FILE, self.txtAbsCorr.GetValue())
        add_to_pickle(PICKLE_FILE, self.txtTakeoff.GetValue())
        add_to_pickle(PICKLE_FILE, self.comboKfacs.StringSelection)
        add_to_pickle(PICKLE_FILE, self.comboStoich.StringSelection)

        # Saving checkbox status to the pickle file. Fixed by Roger
        add_to_pickle(PICKLE_FILE, self.chkKfacs.GetValue())
        add_to_pickle(PICKLE_FILE, self.chkPhaseAnalysis.GetValue())
        add_to_pickle(PICKLE_FILE, self.chkArbAbsCorrection.GetValue())
        add_to_pickle(PICKLE_FILE, self.chkAbsCorr.GetValue())
        add_to_pickle(PICKLE_FILE, self.chkOByStoichiometry.GetValue())

        print(self.cmbPhaseAnalysis.StringSelection)
        print(self.comboArbAbsCorrection.StringSelection)
        print(self.txtAbsCorr.GetValue())
        print(self.txtTakeoff.GetValue())
        print(self.comboKfacs.StringSelection)
        print(self.comboStoich.StringSelection)

        if event is not None:
            event.Skip()

    def _svg_for_wx_rasterization(self, payload):
        """Expand SVG ``use`` nodes that wx.svg's NanoSVG renderer omits.

        Matplotlib stores marker and glyph paths in ``defs`` and references
        them with ``use``.  The canonical SVG remains unchanged for saving and
        browser/notebook use; this only prepares a renderer-compatible copy.
        """
        svg_namespace = '{http://www.w3.org/2000/svg}'
        xlink_href = '{http://www.w3.org/1999/xlink}href'
        root = ElementTree.fromstring(payload)
        identifiers = {
            node.attrib['id']: node for node in root.iter() if 'id' in node.attrib
        }

        def expand(parent):
            for index, child in enumerate(list(parent)):
                if child.tag != svg_namespace + 'use':
                    expand(child)
                    continue
                href = child.get('href') or child.get(xlink_href)
                target = identifiers.get(href[1:]) if href and href.startswith('#') else None
                if target is None:
                    continue
                replacement = deepcopy(target)
                replacement.attrib.pop('id', None)
                transforms = []
                x = child.get('x')
                y = child.get('y')
                if x or y:
                    transforms.append('translate(%s %s)' % (x or '0', y or '0'))
                if child.get('transform'):
                    transforms.append(child.get('transform'))
                if replacement.get('transform'):
                    transforms.append(replacement.get('transform'))
                if transforms:
                    replacement.set('transform', ' '.join(transforms))
                for key, value in child.attrib.items():
                    if key not in ('href', xlink_href, 'x', 'y', 'transform'):
                        replacement.set(key, value)
                parent.remove(child)
                parent.insert(index, replacement)
                expand(replacement)

        expand(root)
        ElementTree.register_namespace('', 'http://www.w3.org/2000/svg')
        ElementTree.register_namespace('xlink', 'http://www.w3.org/1999/xlink')
        return ElementTree.tostring(root, encoding='utf-8', xml_declaration=True)

    def ShowPhaseAnalysisFigures(self, figures):
        """Display each returned SVG artifact in its own non-modal window."""
        if wxsvg is None:
            return 'SVG display support is unavailable; phase-analysis figures remain available for SVG export.'
        figure_ids = [self._phase_figure_layout_id(artifact.id) for artifact in figures]
        existing = getattr(self, '_phase_figure_frames', [])
        if (len(existing) == len(figures) and existing and
                all(not frame.IsBeingDeleted() for frame in existing) and
                [getattr(frame, '_phase_figure_id', None) for frame in existing] == figure_ids):
            try:
                for frame, artifact in zip(existing, figures):
                    frame.SetSvgPayload(self._svg_for_wx_rasterization(artifact.payload))
                    frame.Show()
                    frame.Raise()
                return None
            except Exception:
                # Recreate windows if an existing viewer cannot accept the new SVG.
                self.ClosePhaseAnalysisFigures()
        else:
            self.ClosePhaseAnalysisFigures()
        frames = []
        layouts = []
        try:
            for artifact in figures:
                layout = self._usable_phase_figure_layout(self._phase_figure_layout_id(artifact.id))
                layouts.append(layout)
                frame = SVGFigureFrame(
                    self, artifact.title, self._svg_for_wx_rasterization(artifact.payload),
                    position=layout[0] if layout is not None else wx.DefaultPosition,
                    restored_geometry=layout)
                frame._phase_figure_id = self._phase_figure_layout_id(artifact.id)
                frame.Bind(wx.EVT_CLOSE, self._on_phase_figure_close)
                frames.append(frame)
            self._phase_figure_frames = frames
            for frame, layout in zip(frames, layouts):
                frame.Show()
        except Exception as exc:
            for frame in frames:
                if not frame.IsBeingDeleted():
                    frame.Destroy()
            return 'Could not display SVG phase-analysis figures (%s); they remain available for SVG export.' % exc
        return None

    def ClosePhaseAnalysisFigures(self):
        """Close viewer windows created for the prior phase-analysis result."""
        self._capture_phase_figure_layouts()
        for frame in getattr(self, '_phase_figure_frames', []):
            if not frame.IsBeingDeleted():
                frame.Destroy()
        self._phase_figure_frames = []

    def _capture_phase_figure_layouts(self):
        """Record the current geometry of every live phase-analysis viewer."""
        layouts = getattr(self, 'PhaseFigureLayouts', {})
        for frame in getattr(self, '_phase_figure_frames', []):
            if frame.IsBeingDeleted():
                continue
            figure_id = getattr(frame, '_phase_figure_id', None)
            if not figure_id:
                continue
            position = frame.GetPosition()
            size = frame.GetSize()
            if size.width > 0 and size.height > 0:
                layouts[figure_id] = {
                    'position': [int(position.x), int(position.y)],
                    'size': [int(size.width), int(size.height)],
                }
        self.PhaseFigureLayouts = layouts

    def _on_phase_figure_close(self, event):
        self._capture_phase_figure_layouts()
        event.Skip()

    def _phase_figure_layout_id(self, figure_id):
        result = getattr(self, 'LastAnalysisResult', None)
        phase_analysis = result.options.phase_analysis if result is not None else None
        return '%s:%s' % (phase_analysis or 'phase-analysis', figure_id)

    def _usable_phase_figure_layout(self, figure_id):
        layout = getattr(self, 'PhaseFigureLayouts', {}).get(figure_id)
        if not isinstance(layout, dict):
            return None
        position, size = layout.get('position'), layout.get('size')
        if (not isinstance(position, (list, tuple)) or not isinstance(size, (list, tuple)) or
                len(position) != 2 or len(size) != 2):
            return None
        try:
            x, y = (int(position[0]), int(position[1]))
            width, height = (int(size[0]), int(size[1]))
        except (TypeError, ValueError, OverflowError):
            return None
        if width < 150 or height < 100:
            return None
        for index in range(wx.Display.GetCount()):
            area = wx.Display(index).GetClientArea()
            if width > area.width or height > area.height:
                continue
            if area.x <= x < area.x + area.width and area.y <= y < area.y + area.height:
                # Keep the saved location where possible, but shift a window
                # that now intersects a taskbar or smaller display back into
                # the visible working area rather than discarding it.
                x = builtins.max(area.x, builtins.min(x, area.x + area.width - width))
                y = builtins.max(area.y, builtins.min(y, area.y + area.height - height))
                return (x, y), (width, height)
        return None

    def UpdateInputType(self, InputType=None):
        # If InputType=None, then this is being called because the user changed the input type.
        # If it is 'Counts', 'At%' or 'Wt%' then we are being asked to update the type ourselves.
        if InputType == 'Counts':
            self.rdioInputType.SetSelection(0)
            self.chkOByStoichiometry.Enable()
        elif InputType == 'At%':
            self.rdioInputType.SetSelection(1)
            self.chkOByStoichiometry.Enable()
        elif InputType == 'Wt%':
            self.rdioInputType.SetSelection(2)
            self.chkOByStoichiometry.Enable()
        elif InputType == 'OxWt%':
            self.rdioInputType.SetSelection(3)

        # We use kfacs and arbitrary absorption correction (optionally) for counts.  At% and Wt% don't, ever.
        if self.rdioInputType.GetSelection() == 0:
            self.chkKfacs.SetValue(True)  # By default we'll use kfacs.
            self.chkKfacs.Enable()
            self.comboKfacs.Enable()
        else:
            self.chkKfacs.SetValue(False)  # Uncheck it.
            self.chkKfacs.Disable()  # And also disable it so the user can't check it.  (Breaks our algorithms.)
            self.comboKfacs.Disable()

        # Get the column which is labeled Counts or At % or Wt %.
        col = self.ElementsListCtrl.GetColumn(1)
        # Depending on which radio is checked, choose the right text.
        if self.rdioInputType.GetSelection() == 0:
            col.SetText('Counts')
            self.chkOByStoichiometry.Enable()
        elif self.rdioInputType.GetSelection() == 1:
            col.SetText('At %')
            self.chkOByStoichiometry.Enable()
        elif self.rdioInputType.GetSelection() == 2:
            col.SetText('Wt %')
            self.chkOByStoichiometry.Enable()
        else:
            col.SetText('Ox Wt %')
            # For oxide wt % the user must use stoichiometry.
            self.chkOByStoichiometry.Disable()
            self.chkOByStoichiometry.SetValue(True)
            self.OnStoichSelect(None) # And update the list box.

        # And stuff that modified column back into the ListBox.
        self.ElementsListCtrl.SetColumn(1, col)

    def OnInputType(self, event):  # wxGlade: MyFrame.<event_handler>
        self.UpdateInputType()
        event.Skip()

    def OnStoichSelect(self, event):  # wxGlade: MyFrame.<event_handler>
        # It doesn't matter what the user did.  If they changed any stoichometry settings, we do it all from scratch.
        self.LoadStoichiometryFile()

        # If we are not using oxygen by stoichometry, then mark out the stoichiometry column.
        if self.chkOByStoichiometry.IsChecked() == False:
            for Z in range(1, pb.MAXELEMENT + 1):
                self.ElementsListCtrl.SetItem(Z-1, 2, 'n/a')
            # Make sure the user can only edit the counts column.
            self.ElementsListCtrl.SetEditableColumns((1, ))
        else:
            # If we are using it then we populate it from the self.Stoich variable read by LoadStoichiometryFile
            # Since that was a csv, we have a list of tuples like [('H', 1), ('He', 2), ...]  So index to the right tuple
            # [Z-1] and then into the tuple [Z-1][1]
            for Z in range(1, pb.MAXELEMENT + 1):
                self.ElementsListCtrl.SetItem(Z-1, 2, str(self.Stoich[Z-1][1]))
            # The user can edit the counts column and the stoichiometry column.
            self.ElementsListCtrl.SetEditableColumns((1,2))

        if event != None:
            event.Skip()

    def OnOpen(self, event):  # wxGlade: MyFrame.<event_handler>
        wildcard = ('Stoichiometry Fitter projects (*.stf;*.html)|*.stf;*.html|'
                    'Legacy inputs (*.csv;*.txt)|*.csv;*.txt|Any file (*.*)|*.*')
        dlg = wx.FileDialog(self, 'Open project or input', '', '', wildcard,
                            wx.FD_OPEN | wx.FD_FILE_MUST_EXIST)
        dlg.SetFilterIndex(0)

        if dlg.ShowModal() == wx.ID_CANCEL:
            return
        path = dlg.GetPath()
        try:
            loaded = ProjectPackage.detect_and_load_path(path)
        except Exception as exc:
            wx.MessageBox(str(exc), 'Could not open file', style=wx.OK)
            return

        # Loading and validation above is side-effect free.  GUI state changes
        # only after the complete package/input has passed validation.
        if isinstance(loaded, ProjectPackage.Project):
            self._restore_project(loaded, path)
        else:
            self._restore_imported_input(loaded)

    def _set_input_controls(self, analysis_input):
        type_names = {'Counts': 'Counts', 'At %': 'At%', 'Wt %': 'Wt%', 'Ox Wt %': 'OxWt%'}
        self.UpdateInputType(type_names[StoichiometryCore.normalize_input_type(analysis_input.input_type)])
        values = StoichiometryCore.values_to_vector(analysis_input.values)
        for Z in range(1, pb.MAXELEMENT + 1):
            self.ElementsListCtrl.SetItem(Z - 1, 1, format(float(values[Z - 1]), '.17g'))

    def _restore_imported_input(self, imported):
        self.ClosePhaseAnalysisFigures()
        self.PhaseFigureLayouts = {}
        self.ProjectMetadata = {}
        self._set_input_controls(imported.analysis_input)
        self.OriginalSource = imported.source
        self.CurrentProjectPath = None
        self.CurrentProjectId = None
        self.ArchivedResources = None
        self.ArchivedFingerprint = None
        self.ArchivedInput = None
        self.ArchivedOptions = None
        if hasattr(self, 'LastAnalysisResult'):
            del self.LastAnalysisResult
        self.txtOutput.SetValue('')

    def _restore_project(self, project, opened_path):
        self.ClosePhaseAnalysisFigures()
        self.ProjectMetadata = dict(project.metadata)
        layouts = self.ProjectMetadata.get('phase_figure_layouts', {})
        self.PhaseFigureLayouts = layouts if isinstance(layouts, dict) else {}
        self._set_input_controls(project.input)
        options = project.options
        self.comboStoich.SetValue(project.input.stoichiometry_name or '')
        self.chkOByStoichiometry.SetValue(project.input.stoichiometry is not None)
        if project.input.stoichiometry is None:
            for Z in range(1, pb.MAXELEMENT + 1):
                self.ElementsListCtrl.SetItem(Z - 1, 2, 'n/a')
            self.ElementsListCtrl.SetEditableColumns((1,))
        else:
            for Z, charge in enumerate(project.input.stoichiometry, start=1):
                self.ElementsListCtrl.SetItem(Z - 1, 2, format(float(charge), '.17g'))
            self.ElementsListCtrl.SetEditableColumns((1, 2))

        self.chkKfacs.SetValue(options.kfactors is not None)
        if options.kfactors:
            self.comboKfacs.SetValue(options.kfactors)
        self.chkArbAbsCorrection.SetValue(options.arbitrary_absorption is not None)
        if options.arbitrary_absorption:
            self.comboArbAbsCorrection.SetValue(options.arbitrary_absorption)
        self.chkAbsCorr.SetValue(options.absorption_correction != 0)
        self.txtAbsCorr.SetValue(format(options.absorption_correction * 1000, '.17g'))
        self.txtTakeoff.SetValue(format(options.takeoff, '.17g'))
        self.chkPhaseAnalysis.SetValue(options.phase_analysis is not None)
        if options.phase_analysis:
            self.cmbPhaseAnalysis.SetValue(options.phase_analysis)

        selected = set(options.selected_phases or [])
        for index in range(self.PhasesListCtrl.GetItemCount()):
            state = wx.LIST_STATE_SELECTED if self.PhasesListCtrl.GetItemText(index) in selected else 0
            self.PhasesListCtrl.SetItemState(index, state, wx.LIST_STATE_SELECTED)

        self.CurrentProjectPath = (os.path.splitext(opened_path)[0] + '.stf'
                                   if opened_path.lower().endswith('.html') else opened_path)
        self.CurrentProjectId = project.project_id
        self.OriginalSource = project.original_source
        self.ArchivedResources = project.resources if project.result is not None else None
        self.ArchivedFingerprint = (project.calculation_fingerprint
                                    if project.result is not None else None)
        self.ArchivedInput = project.input
        self.ArchivedOptions = project.options
        if project.result is None:
            if hasattr(self, 'LastAnalysisResult'):
                del self.LastAnalysisResult
            self.txtOutput.SetValue('Not yet calculated.\n')
        else:
            self.LastAnalysisResult = project.result
            self.txtOutput.SetValue(project.result.report_text)
            for warning in project.result.warnings:
                self.txtOutput.AppendText('\nWarning: %s\n' % warning)
            if project.result.figures:
                # Let the main frame finish restoring controls and layout before
                # creating owned top-level figure windows.  Windows otherwise
                # applies its automatic cascade placement during project load.
                wx.CallAfter(self._show_loaded_phase_analysis_figures, project.result.figures)

    def _show_loaded_phase_analysis_figures(self, figures):
        if self.IsBeingDeleted():
            return
        figure_warning = self.ShowPhaseAnalysisFigures(figures)
        if figure_warning:
            self.txtOutput.AppendText('\nWarning: %s\n' % figure_warning)

    def OnSaveInputs(self, event):  # wxGlade: MyFrame.<event_handler>
        dlg = wx.FileDialog(self, '', '', '', 'CSV file (*.csv)|*.csv|Any file (*.*)|*.*',
                            wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT)
        dlg.SetFilterIndex(0)

        if dlg.ShowModal() == wx.ID_CANCEL:
            return

        self.DoSaveInputs(dlg.GetPath())

        return

    def DoSaveInputs(self, FileName):
        analysis_input, _, _ = self._analysis_state_from_controls()
        ProjectPackage.export_input_csv(analysis_input, FileName)

    def OnSaveResults(self, event):  # wxGlade: MyFrame.<event_handler>
        dlg = wx.FileDialog(self, 'Save report', '', '', 'Text file (*.txt)|*.txt|Any file (*.*)|*.*',
                            wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT)
        dlg.SetFilterIndex(0)

        if dlg.ShowModal() == wx.ID_CANCEL:
            return

        self.DoSaveResults(dlg.GetPath())

        return

    def DoSaveResults(self, FileName):
        ProjectPackage.export_report_text(
            self.LastAnalysisResult if hasattr(self, 'LastAnalysisResult') else None,
            FileName)

    def _build_current_project(self):
        self._capture_phase_figure_layouts()
        analysis_input, options, _ = self._analysis_state_from_controls()
        result = None
        if (hasattr(self, 'LastAnalysisResult') and
                self.LastAnalysisResult.input == analysis_input and
                self.LastAnalysisResult.options == options):
            result = self.LastAnalysisResult
        metadata = dict(getattr(self, 'ProjectMetadata', {}))
        if self.PhaseFigureLayouts:
            metadata['phase_figure_layouts'] = self.PhaseFigureLayouts
        else:
            metadata.pop('phase_figure_layouts', None)
        project = ProjectPackage.new_project(
            analysis_input, options, result=result,
            original_source=getattr(self, 'OriginalSource', None),
            project_id=getattr(self, 'CurrentProjectId', None), metadata=metadata)
        self.CurrentProjectId = project.project_id
        return project

    def _save_project_to_path(self, path, overwrite_confirmed=False):
        if not path.lower().endswith('.stf'):
            path += '.stf'
        html_path = os.path.splitext(path)[0] + '.html'
        # Save As uses the native save dialog's overwrite confirmation.  Keep a
        # separate confirmation only when a directly saved project, or an
        # orphaned sidecar report, would be replaced.
        if (os.path.exists(html_path) and not os.path.exists(path)) or (
                os.path.exists(path) and not overwrite_confirmed):
            answer = wx.MessageBox(
                'Replace both project files?\n\n%s\n%s' % (path, html_path),
                'Replace existing project',
                style=wx.YES_NO | wx.NO_DEFAULT | wx.ICON_WARNING)
            if answer != wx.YES:
                return False
        try:
            project = self._build_current_project()
            stf_path, _ = ProjectPackage.save_project_files(project, path)
        except Exception as exc:
            wx.MessageBox(str(exc), 'Could not save project', style=wx.OK)
            return False
        self.CurrentProjectPath = stf_path
        self.ProjectMetadata = dict(project.metadata)
        self.ArchivedResources = project.resources if project.result is not None else None
        self.ArchivedFingerprint = (project.calculation_fingerprint
                                    if project.result is not None else None)
        self.ArchivedInput = project.input
        self.ArchivedOptions = project.options
        return True

    def OnSave(self, event):  # wxGlade: MyFrame.<event_handler>
        if getattr(self, 'CurrentProjectPath', None):
            self._save_project_to_path(self.CurrentProjectPath)
            return
        self.OnSaveAs(event)

    def OnSaveAs(self, event):
        dlg = wx.FileDialog(self, 'Save Stoichiometry Fitter project', '', '',
                            'Stoichiometry Fitter project (*.stf)|*.stf',
                            wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT)
        dlg.SetFilterIndex(0)

        if dlg.ShowModal() == wx.ID_CANCEL:
            return
        self._save_project_to_path(dlg.GetPath(), overwrite_confirmed=True)


    def OnAbout(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnAbout' not implemented!")
        event.Skip()
    def OnDetectorSelect(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'OnDetectorSelect' not implemented!")
        event.Skip()

    # CURRENT END OF CLASS

 # end of class MyFrame

if __name__ == "__main__":
    gettext.install("app")  # replace with the appropriate catalog name

    app = wx.App()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
